### PR TITLE
DBZ-6228 Add support for configuring max.message.bytes of sync topic.

### PR DESCRIPTION
**Pull request by shantanu-sharechat**
Keeping default to 10MB.

### CODE REVIEW

**Review by nancyxu123 — APPROVED** [review]
Looks good to me.

Two things:

1) You will need to update these configs to support large message sizes as well: https://github.com/debezium/debezium-connector-spanner/blob/ad4e02f48633fc1bcadba9c71096ec1b90bdff7e/src/main/java/io/debezium/connector/spanner/SpannerConnectorConfig.java#L80

2) I am working on a optimization to the connector to reduce the size of messages passed between tasks. Optimization is expected to be completed soonish.

**Comment by shantanu-sharechat** [comment]
Thanks @nancyxu123 for mentioning, the current config is 100MB which should be sufficient for now? 
Also for 2.) Currently are older partitions removed from task sync state or is there any other cleanup logic? If not then (2) needs to be done otherwise the size will keep on increasing.

**Comment by nancyxu123** [comment]
> 

Hi Shantanu, yes we do remove older partitions. I have an optimization to just have tasks communicate deltas rather than the whole state, but it shouldn't impact processing for you for now, since it is just an optimization. Let me know if that scenario changes.

**Comment by jpechane** [comment]
@shantanu-sharechat Applied, thanks. Could you please prepare a new Jira issue and PR with pass-through connection/topic configuration as was proposed on the chat so it is no longer necessary to pass it one by one?

**Comment by shantanu-sharechat** [comment]
@jpechane have made the issue https://issues.redhat.com/browse/DBZ-6262, will start looking into changes

**Pull request merged**
